[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
tlv = { path = "../tlv"}
# tlv = { git = "https://github.com/UnifyAir/tlv-compiler.git", package = "tlv", branch = "master" }


